name: Generate Snake 🐍

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Generate the snake SVG
        uses: Platane/snk@v2
        with:
          github_user_name: FAKE-SURYA
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to the output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: output
          publish_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
